---
name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
    env:
      BUILD_TOOLS_PATH: C:\apps\build-tools\
    steps:
      - run: echo $env:BUILD_TOOLS_PATH | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        if: startsWith(matrix.os, 'windows')

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Build tools
        if: startsWith(matrix.os, 'windows')
        run: git clone https://git.anotherfoxguy.com/AnotherFoxGuy/build-tools.git %BUILD_TOOLS_PATH%
        shell: cmd

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.1

      - name: Cache conan packages
        uses: actions/cache@v3
        with:
          key: conan-${{ runner.os }}-${{ hashFiles('conanfile.py') }}
          path: ~/.conan2/

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          cache: 'true'
          version: 6.4.0
          modules: qt5compat qtpositioning
          dir: "${{ github.workspace }}/qt/"

      - name: Add conan remote
        run: conan remote add ror-conan https://git.anotherfoxguy.com/api/packages/rorbot/conan -f

      - name: Run Conan (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
          conan remote add ror-conan https://git.anotherfoxguy.com/api/packages/rorbot/conan -f
          conan install . -b missing -pr:b=tools/conan-profiles/vs-22-release-ninja -pr=tools/conan-profiles/vs-22-release-ninja
        shell: cmd

      - name: Build
        run: |
          cmake --preset conan-release -DCMAKE_INSTALL_PREFIX=redist
          ninja

      - name: Install
        run: ninja install

      - name: Upload redist folder
        uses: actions/upload-artifact@v3
        with:
          name: diesel-${{ runner.os }}
          path: redist
